// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.3
// source: v1/tunnel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlCode defines the core intent of a Packet
// This is the "verb" of the protocol
type ControlCode int32

const (
	// Default value, indicates this is a standard business data packet
	ControlCode_DATA ControlCode = 0
	// Indicates an error occurred in processing the CONN for a conn_id
	// The error_message field should contain error details
	ControlCode_ERROR ControlCode = 1
	// Graceful shutdown: Sent by agent to hub to indicate it's about to go offline
	ControlCode_DRAIN ControlCode = 2
)

// Enum value maps for ControlCode.
var (
	ControlCode_name = map[int32]string{
		0: "DATA",
		1: "ERROR",
		2: "DRAIN",
	}
	ControlCode_value = map[string]int32{
		"DATA":  0,
		"ERROR": 1,
		"DRAIN": 2,
	}
)

func (x ControlCode) Enum() *ControlCode {
	p := new(ControlCode)
	*p = x
	return p
}

func (x ControlCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_tunnel_proto_enumTypes[0].Descriptor()
}

func (ControlCode) Type() protoreflect.EnumType {
	return &file_v1_tunnel_proto_enumTypes[0]
}

func (x ControlCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlCode.Descriptor instead.
func (ControlCode) EnumDescriptor() ([]byte, []int) {
	return file_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

// Packet is the atomic unit transmitted in the tunnel
type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Used to associate requests and responses, implements multiplexing ID
	// For tunnel-level messages (such as PING/PONG/DRAIN), can be 0
	ConnId int64 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	// [Key optimization] The intent code of the packet, makes processing logic clearer
	Code ControlCode `protobuf:"varint,2,opt,name=code,proto3,enum=tunnel.v1.ControlCode" json:"code,omitempty"`
	// Business payload, only meaningful when code = DATA
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Error message, only meaningful when code = ERROR
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_v1_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_v1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetConnId() int64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *Packet) GetCode() ControlCode {
	if x != nil {
		return x.Code
	}
	return ControlCode_DATA
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Packet) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_v1_tunnel_proto protoreflect.FileDescriptor

const file_v1_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/tunnel.proto\x12\ttunnel.v1\"\x86\x01\n" +
	"\x06Packet\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\x03R\x06connId\x12*\n" +
	"\x04code\x18\x02 \x01(\x0e2\x16.tunnel.v1.ControlCodeR\x04code\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*-\n" +
	"\vControlCode\x12\b\n" +
	"\x04DATA\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\t\n" +
	"\x05DRAIN\x10\x022E\n" +
	"\rTunnelService\x124\n" +
	"\x06Tunnel\x12\x11.tunnel.v1.Packet\x1a\x11.tunnel.v1.Packet\"\x00(\x010\x01B1Z/github.com/xuezhaojun/multiclustertunnel/api/v1b\x06proto3"

var (
	file_v1_tunnel_proto_rawDescOnce sync.Once
	file_v1_tunnel_proto_rawDescData []byte
)

func file_v1_tunnel_proto_rawDescGZIP() []byte {
	file_v1_tunnel_proto_rawDescOnce.Do(func() {
		file_v1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tunnel_proto_rawDesc), len(file_v1_tunnel_proto_rawDesc)))
	})
	return file_v1_tunnel_proto_rawDescData
}

var file_v1_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_tunnel_proto_goTypes = []any{
	(ControlCode)(0), // 0: tunnel.v1.ControlCode
	(*Packet)(nil),   // 1: tunnel.v1.Packet
}
var file_v1_tunnel_proto_depIdxs = []int32{
	0, // 0: tunnel.v1.Packet.code:type_name -> tunnel.v1.ControlCode
	1, // 1: tunnel.v1.TunnelService.Tunnel:input_type -> tunnel.v1.Packet
	1, // 2: tunnel.v1.TunnelService.Tunnel:output_type -> tunnel.v1.Packet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_tunnel_proto_init() }
func file_v1_tunnel_proto_init() {
	if File_v1_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tunnel_proto_rawDesc), len(file_v1_tunnel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tunnel_proto_goTypes,
		DependencyIndexes: file_v1_tunnel_proto_depIdxs,
		EnumInfos:         file_v1_tunnel_proto_enumTypes,
		MessageInfos:      file_v1_tunnel_proto_msgTypes,
	}.Build()
	File_v1_tunnel_proto = out.File
	file_v1_tunnel_proto_goTypes = nil
	file_v1_tunnel_proto_depIdxs = nil
}
