apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://mctunnel-server:8080
    insecure-skip-tls-verify: true
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: test-user
  name: test-context
current-context: test-context
users:
- name: test-user
  user:
    token: fake-token-for-docker-compose-testing
