apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: multiclustertunnel
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: multiclustertunnel-e2e
    app.kubernetes.io/instance: {{ .Name }}
    e2e-test: "true"
  annotations:
    description: "Service account for MultiClusterTunnel server component in e2e tests"
automountServiceAccountToken: true
