apiVersion: v1
kind: Secret
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: multiclustertunnel
    app.kubernetes.io/component: certificates
    app.kubernetes.io/part-of: multiclustertunnel-e2e
    certificate-type: server
    e2e-test: "true"
  annotations:
    description: "Server certificate for MultiClusterTunnel e2e testing"
type: kubernetes.io/tls
data:
  tls.crt: {{ .ServerCert | b64enc }}
  tls.key: {{ .ServerKey | b64enc }}
  ca.crt: {{ .CACert | b64enc }}
